[package]
name = "tree"
version = "0.2.0"
description = "a better tree command"
homepage = "https://github.com/vicvenscob/tree"
license = "MIT"
url = "https://github.com/vicvenscob/tree/archive/refs/heads/main.tar.gz"
depends = []
post_install = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path && $HOME/.cargo/bin/rustc tree.rs -o /usr/local/bin/tree"

[package.files]
